import type { CSSProperties } from "react";

type Styles = Record<string, CSSProperties>;

// CTC-inspired theme: white bg, red accent, clean professional
export const theme = {
  red: "#ed1b24",
  redHover: "#c8151d",
  dark: "#363636",
  mid: "#555555",
  muted: "#888888",
  border: "#e0e0e0",
  bg: "#f5f5f5",
  cardBg: "#ffffff",
};

export const s: Styles = {
  screen: {
    minHeight: "100vh",
    background: theme.bg,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: "clamp(16px, 5vw, 40px) clamp(8px, 3vw, 16px)",
    fontFamily: "'Open Sans', 'Segoe UI', Arial, sans-serif",
  },
  card: {
    background: theme.cardBg,
    border: `1px solid ${theme.border}`,
    borderRadius: 12,
    padding: "clamp(20px, 8vw, 40px)",
    width: "100%",
    maxWidth: "min(480px, 90vw)",
    boxShadow: "0 4px 20px rgba(0,0,0,0.08)",
  },
  title: {
    color: theme.dark,
    fontSize: "clamp(24px, 8vw, 34px)",
    fontWeight: 700,
    margin: "0 0 6px",
    letterSpacing: -0.5,
  },
  subtitle: {
    color: theme.muted,
    fontSize: "clamp(13px, 4vw, 15px)",
    margin: 0,
  },
  privacyBox: {
    background: "#fafafa",
    border: `1px solid ${theme.border}`,
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
  },
  stravaBtn: {
    width: "100%",
    padding: "clamp(12px, 3vw, 14px) clamp(20px, 5vw, 24px)",
    background: theme.red,
    color: "white",
    border: "none",
    borderRadius: 9999,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    boxShadow: "0 4px 16px rgba(237,27,36,0.3)",
  },
  section: { marginBottom: 20 },
  label: {
    display: "block",
    color: theme.mid,
    fontSize: 13,
    marginBottom: 8,
    fontWeight: 600,
  },
  select: {
    width: "100%",
    padding: "10px 14px",
    background: "#ffffff",
    border: `1px solid ${theme.border}`,
    borderRadius: 8,
    color: theme.dark,
    fontSize: 14,
    cursor: "pointer",
    outline: "none",
  },
  optionBtn: {
    flex: 1,
    padding: "10px 16px",
    background: "transparent",
    border: `1px solid ${theme.border}`,
    borderRadius: 8,
    color: theme.mid,
    fontSize: 14,
    cursor: "pointer",
  },
  optionBtnActive: {
    background: "rgba(237,27,36,0.08)",
    border: `1px solid ${theme.red}`,
    color: theme.red,
    fontWeight: 700,
  },
  primaryBtn: {
    width: "100%",
    padding: "clamp(12px, 3vw, 14px) clamp(20px, 5vw, 24px)",
    background: theme.red,
    color: "white",
    border: "none",
    borderRadius: 9999,
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 16px rgba(237,27,36,0.3)",
  },
  progressBar: {
    width: "clamp(200px, 70vw, 280px)",
    height: 4,
    background: theme.border,
    borderRadius: 999,
    margin: "28px auto 0",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: `linear-gradient(90deg, ${theme.red}, #ff6b6b)`,
    borderRadius: 999,
    animation: "progress 3s linear forwards",
    width: "0%",
  },
  dashHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  resetBtn: {
    padding: "8px 16px",
    background: "transparent",
    border: `1px solid ${theme.border}`,
    borderRadius: 9999,
    color: theme.muted,
    fontSize: 13,
    cursor: "pointer",
  },
  disclaimer: {
    background: "rgba(237,27,36,0.05)",
    border: "1px solid rgba(237,27,36,0.2)",
    borderRadius: 8,
    padding: "12px 16px",
    color: theme.mid,
    fontSize: 12,
    lineHeight: 1.6,
    marginBottom: 20,
  },
  statsRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    marginBottom: 16,
    width: "100%",
  },
  statCard: {
    background: theme.cardBg,
    border: `1px solid ${theme.border}`,
    borderRadius: 10,
    padding: "14px 12px",
    textAlign: "center",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
  },
  statValue: {
    color: theme.dark,
    fontSize: 20,
    fontWeight: 800,
    marginBottom: 4,
  },
  statLabel: { color: theme.muted, fontSize: 11 },
  compGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
    marginBottom: 24,
    width: "100%",
  },
  compCard: {
    background: theme.cardBg,
    border: `1px solid ${theme.border}`,
    borderRadius: 12,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
  },
  updateBtn: {
    marginTop: 12,
    padding: "6px 14px",
    background: "transparent",
    border: `1px solid ${theme.border}`,
    borderRadius: 9999,
    color: theme.muted,
    fontSize: 11,
    cursor: "pointer",
  },
  motivationCard: {
    background: "rgba(237,27,36,0.04)",
    border: "1px solid rgba(237,27,36,0.15)",
    borderRadius: 12,
    padding: "clamp(12px, 4vw, 18px) clamp(16px, 5vw, 24px)",
    textAlign: "center",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
    padding: "clamp(8px, 3vw, 16px)",
  },
  modal: {
    background: theme.cardBg,
    border: `1px solid ${theme.border}`,
    borderRadius: 12,
    padding: "clamp(16px, 6vw, 32px)",
    width: "100%",
    maxWidth: "min(400px, 90vw)",
    fontFamily: "'Open Sans', 'Segoe UI', Arial, sans-serif",
    boxShadow: "0 10px 40px rgba(0,0,0,0.15)",
  },
  spinner: {
    width: 40,
    height: 40,
    border: `4px solid ${theme.border}`,
    borderTop: `4px solid ${theme.red}`,
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    margin: "0 auto 16px",
  },
};
